#!/bin/bash
#$ -S /bin/bash
#$ -N Append_Opt
#$ -cwd
#$ -e ./result/optimal.log
#$ -o ./result/optimal_output.dat
#$ -t 1-2:1
#$ -V
METHODS=("DUMMY NORMAL" "CHIBANORMAL FLAT" "SUBHILL NORMAL")
REFERENCE_SIZES="3,10"
ECOLIREF=./data/reference.fa
MODELPATH=./data/template.model
QUERIES=./data/test.dat
QUERY_SIZES=(00 1000 450)
METHOD=${METHODS[$SGE_TASK_ID]}
QUERYSIZE=${QUERY_SIZES[$SGE_TASK_ID]}

./target/release/datagenerator $QUERIES $MODELPATH $ECOLIREF $QUERYSIZE $REFERENCE_SIZES $METHOD TEST
